blank_issues_enabled: false
contact_links:
  - name: Whipay DevOps
    url: https://github.com/whipay/issues/issues/new/choose
    about: Please create an issue here if you have an idea or want to report a problem
